[ADD] 상세페이지 조회 기능
wecode-bootcamp-korea/38-1st-Wedidas-backend pull request #11
Opened 2022-10-25 12:40 UTC by JeongDoYoung2

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
1.상세페이지 조회기능

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1.product/:productId 입력시 상세 데이터 ( 상세설명 , 상세 이미지 , 이름 , 성별 ,카테고리) 전송

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- sub query문에 대해 알게되었습니다

## :: 기타 질문 및 특이 사항

2022-10-25 23:49 UTC, sangwoong03 requested changes
sql 파일이 같이 올라와있네요 도영님~!

push 전에 어떤 파일들이 staging되고 commit 되는지 확인 후에 push하는 습관을 들여주세요.

해당 파일 git rm --cached 명령어를 통해 삭제 후 github상에서 삭제되면 다시 리뷰 진행할게요!

2022-10-26 12:40 UTC, JeongDoYoung2 commented
멘토님 git rm --cached wedidas.sql 했는데 아직 파일이 남아있어서 사라진지 구분이 안갑니다. 사라진건가요?

2022-10-26 23:52 UTC, sangwoong03 requested changes
고생하셨습니다! 수정사항 한번 더 확인해주세요~!

2022-10-26 23:52 UTC, sangwoong03 commented on controllers/productController.js
> +    let productId = parseInt(req.params.productId);
`productId`는 추후 재할당되지 않는 변수이기 때문에 `const` 키워드를 사용하는 것이 좋을 것 같습니다!
```suggestion
    const productId = parseInt(req.params.productId);
```

2022-10-26 23:52 UTC, sangwoong03 commented on models/productDao.js
> +        ) AS stocksize
마이너한 부분이지만 포맷팅 (들여쓰기) 다시 한번 신경써주세요!
```suggestion
      sc.name AS cateogory,
      JSON_ARRAYAGG(pi.image_url) AS images,
      (	
        SELECT
          JSON_ARRAYAGG(
            JSON_OBJECT(
              'id', po.id,
              'footSize', s.foot_size,
              'stock', po.stock
          )
        )
        FROM product_options AS po
          INNER JOIN sizes AS s ON s.id = po.size_id
          WHERE po.product_id = p.id
      ) AS stocksize
```

2022-10-26 23:52 UTC, sangwoong03 commented on models/productDao.js
> +const productDetails = async (productId) => {
함수명을 좀 더 명확하게 지어주면 더 좋을 것 같아요!

```suggestion
const getProductDetails = async (productId) => {
```

2022-10-26 23:52 UTC, sangwoong03 commented on services/productService.js
> +    return await productDao.productDetails(productId);
Dao 함수명 변경 시 해당 부분 변경도 고려해주세요!
```suggestion
    return await productDao.getProductDetails(productId);
```

2022-10-26 23:58 UTC, JeongDoYoung2 commented on services/productService.js
> +    return await productDao.productDetails(productId);
전부 수정 완료했습니다!

2022-10-27 00:33 UTC, sangwoong03 commented
도영님! 컨플릭트 해결해주세요~!

2022-10-27 08:33 UTC, sangwoong03 approved these changes
LGTM 👍

2022-10-27 08:33 UTC, merged