[add] 로그인 기능 구현
wecode-bootcamp-korea/38-1st-Wedidas-backend pull request #4
Opened 2022-10-19 11:08 UTC by csongin

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 아이디, 비밀번호 입력창을 사용한 로그인 기능 구현 

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)

1. 로그인 데이터 처리 (예시 - 백엔드)
- 조건문과 정규식을 이용한 email과 password 유효성 검사를 진행
- 유효섬 검사를 통과하지 못 할 경우 에러 메시지를 반환 예외 처리 구현
- 프론트와 통신 연결 테스트 성공
- 토큰 값 전달 완료

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 회원가입, 로그인 실습 과정이 큰 도움이 되었습니다.

<br />

## :: 기타 질문 및 특이 사항
-

2022-10-20 01:39 UTC, sangwoong03 requested changes
고생하셨습니다.

코드 전반적인 indentation (들여쓰기)을 수정해주세요!

파일 별 tabsize가 2 또는 4로 상이한 것 같습니다. 하나로 맞추어 수정해주세요!

2022-10-20 01:39 UTC, sangwoong03 commented on services/userService.js
> +		error.statusCode = 401;
`status_code: 401` 관련해서 자료를 찾아보고 수정해주세요.

클라이언트에게 보여지는 적절한 에러메시지와 상태코드를 사용하는 것도 중요합니다!

상태코드에 대한 학습 후 다른 부분도 수정해주세요~!

2022-10-20 01:39 UTC, sangwoong03 commented on services/userService.js
> +	)
환경변수를 사용함에 있어 협업하는 개발자들에게도 어떤 환경변수가 사용되었는지 공유가 되어야 합니다.

`.env.sample` 파일에서도 환경변수와 관련된 샘플 내용을 수정해주세요!

2022-10-20 01:39 UTC, sangwoong03 commented on models/userDao.js
> +}
가독성을 위해 해당 부분의 indentation과 tabsize를 수정해주세요!

```suggestion
const getUserByEmail = async (email) => {
  const result = await dataSource.query(`
    SELECT 
      id,
      name,
      email,
      password,
      birthday,
      phone_number
    FROM users
    WHERE email=?`, [email]
    );
  return result[0];
}
```

2022-10-20 01:39 UTC, sangwoong03 commented on models/userDao.js
> +}
해당 부분도 마찬가지입니다!

2022-10-20 01:39 UTC, sangwoong03 commented on services/userService.js
> +}
해당 코드는 어떤 기능을 위해 사용되는 코드인가요?

2022-10-20 04:11 UTC, csongin commented on services/userService.js
> +}
- service에서 필요없는 기능인거 같습니다. 삭제하도록 하겠습니다!

2022-10-20 05:08 UTC, sangwoong03 requested changes

2022-10-20 05:08 UTC, sangwoong03 commented on models/userDao.js
> +}
포매팅 다시 수정해주세요.

해당 기능에서 불필요한 코드는 삭제해주세요.

2022-10-20 09:06 UTC, sangwoong03 requested changes

2022-10-20 09:06 UTC, sangwoong03 commented on utils/regex.js
> +}
모듈 분리를 잘 해주신 것 같습니다.

다만 추후에 이메일 혹은 비밀번호에 대한 유효성만 검사하는 경우 함수의 매개변수로 들어오는 인자 값에 대해 오류가 발생할 것 같네요.

혹시 지금 분리할 수 있다면, 분리가 가능할까요?

예를 들면, 이메일 하나에 대한 유효성 검사 모듈 1개 / 비밀번호 유효성 검사 모듈 1개

2022-10-20 09:06 UTC, sangwoong03 commented on utils/regex.js
> +}
어려울 것 같으면 댓글 남겨주세요~

2022-10-20 10:33 UTC, csongin commented on utils/regex.js
> +}
반영했습니다.
말씀하신 내용이 맞는지 모르겠네요ㅎㅎ

2022-10-21 01:16 UTC, sangwoong03 approved these changes
LGTM 👍

2022-10-21 01:16 UTC, merged