[add] wishlist 기능 구현
wecode-bootcamp-korea/38-1st-Wedidas-backend pull request #6
Opened 2022-10-21 00:57 UTC by csongin

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 위시리스트 기능 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 위시리스트의 추가, 조회, 삭제 기능 구현
- 요청 값이 없을 경우 에러 메시지를 반환하게 구현
- 쿼리문을 이용한 생성 및 조회 삭제 기능 구현

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 위시리스트에 담기는 과정에 대해 생각하게 되었습니다.
- 데이터베이스에 담긴 테이블의 관계를 참고하여 원하는 컬럼 값을 조회하는 쿼리문을 공부하게 되었습니다.

<br />

## :: 기타 질문 및 특이 사항
-

2022-10-21 01:48 UTC, sangwoong03 requested changes

2022-10-21 01:48 UTC, sangwoong03 commented on routes/wishlistRouter.js
> +router.delete('/:userId/:productId', wishlistController.deleteWishlist);
위시리스트는 유저가 로그인을 했을 때 보여주어야 하는 유저의 개인 정보 중 하나로 서비스 기획을 하셨을 것입니다.

하지만 다음과 같이 path parameter를 통해 접근 할 수 있게 되면 누구나 userId 값만 갖고 특정 유저의 위시리스트를 파악할 수 있는 문제점이 발생합니다.

그렇기 때문에 유저가 로그인을 한 서비스를 구현하기 위해 인가 과정이 필요합니다.

로그인을 통해 토큰을 발급하여 해당 유저를 인증하는 과정을 연습해본 적이 있을 것입니다.

토큰을 다시 복호화하여 얻은 정보를 통해 해당 유저의 권한을 인가하는 과정이 필요할 것 같습니다.

인가 과정을 천천히 고민해보시고 코드를 전반적으로 수정해주세요.

2022-10-21 06:30 UTC, sangwoong03 requested changes
고생하셨습니다~!

다만, 토큰을 받아오는 미들웨어를 사용했을 때 유저 정보를 확인하는 방법에 대해 다시 한번 고민해주세요!

2022-10-21 06:30 UTC, sangwoong03 commented on utils/auth.js
> +  const decoded = await promisify(jwt.verify)(accessToken, process.env.JWT_SECRET);
`promisfy`를 사용하신 이유가 있나요?

2022-10-21 06:30 UTC, sangwoong03 commented on controllers/wishlistController.js
> +  const { userId, productId } = req.body;
해당 코드 작동이 잘 되나요 송인님!?

2022-10-21 06:30 UTC, sangwoong03 commented on controllers/wishlistController.js
> +});
indentation 수정 부탁드립니다~!

2022-10-21 06:36 UTC, csongin commented on controllers/wishlistController.js
> +  const { userId, productId } = req.body;
네! 잘 작동됩니다

2022-10-21 07:10 UTC, csongin commented on utils/auth.js
> +  const decoded = await promisify(jwt.verify)(accessToken, process.env.JWT_SECRET);
동기 방식의 함수 수행을 비동기 방식으로 구현하기 위해서 작성하였으나, 비동기 방식으로 구현해야할 이유를 찾지 못했습니다.
이 부분은 수정하겠습니다!

2022-10-21 09:28 UTC, sangwoong03 requested changes

2022-10-21 09:28 UTC, sangwoong03 commented on utils/auth.js
> +const { promisify } = require('util');
코드 상 사용하지 않는 패키지는 삭제해주세요!

2022-10-21 11:13 UTC, csongin commented on utils/auth.js
> +const { promisify } = require('util');
jwt는 해당파일 내에서 불려지기 때문에 필요할 것 같습니다.
토큰값을 인가하는 과정에서 userService, userDao 로직이 일부 추가되었습니다!

2022-10-24 00:41 UTC, sangwoong03 requested changes

2022-10-24 00:41 UTC, sangwoong03 commented on models/userDao.js
> +
해당 부분 들여쓰기 수정 후 다시 push 해주세요~!

2022-10-24 02:32 UTC, sangwoong03 requested changes

2022-10-24 02:32 UTC, sangwoong03 commented on models/wishlistDao.js
> +    w.user_id AS id,
user의 id를 받아오기 때문에 해당 컬럼 별칭을 userId로 바꾸는 것이 더 적절할 것 같습니다!

2022-10-24 02:32 UTC, sangwoong03 commented on models/wishlistDao.js
> +  WHERE u.id = ?
송인님~ 조건절을 다음과 같이 작성했을 때 원하는 값을 도출해낼 수 있었나요??

2022-10-24 02:32 UTC, sangwoong03 commented on controllers/wishlistController.js
> +  res.status(201).json({ message: '위시리스트 저장 성공' });
송인님! 에러메시지를 한글로 전달할 때 인코딩 방법에 따라 한글이 깨지는 현상이 발생할 수 있습니다.

End to end 통신 간 에러메시지가 깨지는 문제는 없었나요??

2022-10-24 04:24 UTC, csongin commented on models/wishlistDao.js
> +  WHERE u.id = ?
네! 잘 도출됩니다

2022-10-24 04:35 UTC, csongin commented on controllers/wishlistController.js
> +  res.status(201).json({ message: '위시리스트 저장 성공' });
convention 통일을 위해 영어로 수정하겠습니다!

2022-10-24 08:46 UTC, sangwoong03 approved these changes
LGTM 👍

2022-10-24 08:47 UTC, merged