Feature/carts
wecode-bootcamp-korea/38-1st-Wedidas-backend pull request #7
Opened 2022-10-22 12:50 UTC by csongin

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 장바구니 기능 구현(장바구니 담기, 장바구니 확인, 장바구니 삭제)

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 장바구니 생성, 조회, 삭제 기능 구현
- query 문을 이용해서 create, select, delete 로직 수행
- postman을 이용해서 테스트 완료
- userId와 product_option_id 값을 받아와서 장바구니에 담기 기능 구현
- userId를 받아와 장바구니 조회 기능 구현
- userId와 장바구니에 담긴 produtcId를 받아와 장바구니의 상품 삭제 기능 구현

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 장바구니에 물건이 담기고, 조회하고 삭제하는 과정을 깊게 생각해보게 되었습니다.
- query문을 활용하는 방법을 배웠습니다.
- 테이블 관계에 대해서 size와 product를 매칭하는 것이 어려웠습니다.

<br />

## :: 기타 질문 및 특이 사항
- 조회와 삭제 기능의 경우 controller에서 응답메시지를 작성하는 것이 좋은가요? 별도의 메시지를 보내지 않아도 상관이 없는지 궁금합니다. 
- delete의 경우 204 메시지를 띄우고 별도의 메시지를 보내지 않는 것으로 알고 있습니다.

2022-10-24 01:24 UTC, sangwoong03 commented
> 조회와 삭제 기능의 경우 controller에서 응답메시지를 작성하는 것이 좋은가요? 별도의 메시지를 보내지 않아도 상관이 없는지 궁금합니다.

조회의 경우 반환되는 값이 장바구니에 대한 정보가 JSON 값으로 반환이 되기 때문에 별도의 메시지가 필요하지 않습니다.

삭제의 경우 반환되는 값이 없으므로 상태코드가 204로 잘 작성해주셨어요.
만약 좀 더 구체적인 상태메시지를 반환하고 싶다면, 요청에 다른 응답 코드는 200으로 변경 한 다음 메시지로 `DELETED_SUCCESS` 등의 메시지를 반환할 수 있을 것 같네요!

2022-10-24 01:24 UTC, sangwoong03 requested changes

2022-10-24 01:24 UTC, sangwoong03 commented on controllers/cartController.js
> +  const userId = req.query.id;
유저의 정보가 url 쿼리에 있다면, 제 3자가 유저의 정보만 가지고도 장바구니에 접근할 수 있을 것 같네요.

토큰을 활용하여 장바구니에 상품을 추가할 수 있도록 수정해주세요.

2022-10-24 01:24 UTC, sangwoong03 commented on controllers/cartController.js
> +  const { userId } = req.query;
해당 부분도 토큰을 복호화하였을 때 유저 정보를 활용하면 좋을 것 같네요!

2022-10-24 01:24 UTC, sangwoong03 commented on controllers/cartController.js
> +  const { userId, productId } = req.query;
이 부분도 마찬가지입니다!

2022-10-24 01:24 UTC, sangwoong03 commented on models/cartDao.js
> +const deleteCart = async (userId, productId) => {
productId를 받아서 장바구니 테이블의 product_option_id와 비교하는 것이 논리적으로 맞지 않아보입니다!

다시 생각해보시고 수정해주세요!

2022-10-24 01:24 UTC, sangwoong03 commented on models/cartDao.js
> +}
productOption에 바로 접근할 수 있을지가 궁금하네요!

유저가 size를 고른 상태에서 바로 productOption으로 접근할 수 있는 기획인가요?

2022-10-24 01:24 UTC, sangwoong03 commented on models/cartDao.js
> +}
carts 테이블에서 where 절로 users의 테이블의 id를 비교하는 로직으로 작성하신 게 맞는 건가요??

2022-10-25 08:41 UTC, sangwoong03 requested changes
송인님 고생하셨습니다.

우선 리뷰 천천히 읽어보시고, 이해되는 부분에 대해서 수정 작업 진행해주세요!

2022-10-25 08:41 UTC, sangwoong03 commented on controllers/cartController.js
> +  if ( !userId || !productId || !sizeId ) {
송인님~! 이미 auth middleware를 거쳤기 때문에 userId가 존재하지 않는 경우에는 미들웨어에서 에러에 대한 예외처리를 진행합니다.

따라서 해당 부분에서 userId에 대한 키 존재 유무를 다시 판단할 필요가 없을 것 같습니다!

2022-10-25 08:41 UTC, sangwoong03 commented on controllers/cartController.js
> +  }
해당 부분도 마찬가지입니다!

2022-10-25 08:41 UTC, sangwoong03 commented on controllers/cartController.js
> +  }
해당 부분도 마찬가지입니다!

2022-10-25 08:41 UTC, sangwoong03 commented on models/cartDao.js
> +}
장바구니에 대한 데이터를 보내줄 때 장바구니에 대한 id 값을 포함하여 보내주세요!

데이터베이스 관점에서 보았을 때 데이터를 구분하는 고유의 값은 id로 설정하였습니다.
추가로 cart의 id를 보냈을 때 장바구니를 삭제할 수 있는 로직이 좀 더 간결해질 것 같습니다.


getCart라는 함수 네이밍도 좋지만, 특정 유저의 정보를 통해 장바구니 정보를 얻는다는 의미를 담아 함수 이름을 다음과 같이 수정할 수도 있을 것 같습니다!
```suggestion
const getCartByUserId = async (userId) => {
  const result = await appDataSource.query(`
    SELECT
      c,id,
      c.user_id AS userId,
      c.product_option_id AS productOptionId,
      c.count,
      po.product_id AS productId,
      po.size_id AS sizeId,
      p.thumbnail_image_url AS thumbnailUrl,
      p.name,
      p.price,
      s.foot_size AS footSize,
      po.stock
    FROM carts AS c
    JOIN users AS u ON c.user_id = u.id
    JOIN product_options AS po ON c.product_option_id = po.id
    JOIN products p ON po.product_id = p.id
    JOIN sizes AS s ON po.size_id = s.id
    WHERE c.user_id=?`,
    [userId]
  );
  return result;
}
```

2022-10-25 08:41 UTC, sangwoong03 commented on models/cartDao.js
> +  `);
장바구니에 넣었을 때 productOptions 테이블의 stock값도 변경을 해야된다면 장바구니에 추가된 count만큼 stock에서 줄여주어야 할 것 같습니다!
where 절에서의 조건도 좀 더 명확한 조건을 한번 고민해주세요!

```suggestion
const updateCart = async (userId, count, stock) => {
  const result = await appDataSource.query(`
    UPDATE carts AS c, product_options AS po
    SET c.count=${count}, po.stock = stock - ${count}
    WHERE user_id=${userId} AND stock=${stock} AND ${count} <= ${stock}
  `);
```

2022-10-25 08:41 UTC, sangwoong03 commented on models/cartDao.js
> +}
장바구니 자체의 id를 받아오는 경우 다음과 같이 수정할 수 있을 것 같습니다.
```suggestion
const deleteCart = async (cartId) => {
  const result = await appDataSource.query(`
    DELETE
    FROM carts
    WHERE id = ?`,
  [cartId]
  );
  return result;
}
```

2022-10-25 08:41 UTC, sangwoong03 commented on models/cartDao.js
> +  `)
해당 부분은 같이 고민해서 리팩토링 해볼 필요가 있을 것 같네요!
쿼리 짜느라 고생하셨습니다..

우선은 방향성은 다음과 같이 잡아볼게요!

- `productId` `sizeId`를 통해 productOptionId를 받아옴.
- `userId` `productOptionId`를 통해 cartId 조회
- cartId가 존재한다면, 해당 데이터에 수량 추가 혹은 중복체크
- cartId가 존재하지 않는다면 createCart 함수 실행

이해 안가면 DM이나 댓글 부탁드려요!

2022-10-25 08:55 UTC, csongin commented on models/cartDao.js
> +  `);
음.. 이 부분은 stock의 경우는 장바구니 기능 자체가 여러 user가 장바구니에 담아도 실제 주문으로 이루어지지 않으면 stock이 차감되지 않아야 한다고 생각해서 그렇게 로직을 구성하였습니다.

2022-10-27 07:33 UTC, sangwoong03 approved these changes
LGTM 👍

2022-10-27 07:34 UTC, merged