[add] 가격순 , 최신순 필터기능
wecode-bootcamp-korea/38-1st-Wedidas-backend pull request #8
Opened 2022-10-23 08:00 UTC by JeongDoYoung2

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- queryparameter sort값에 따른 정렬

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
sort = high => 높은 가격순 정렬
sort = low => 낮은 가격순 정렬
sort = new => 최신순 정렬
sort = old => 가장 오래된 순 정렬
sort의 값이 없을 땐 기존 정렬 구현

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 변수에 쿼리문을 작성하면 보다 많은 기능을 구현할 수 있다는 것을 알게 됐습니다.

## :: 기타 질문 및 특이 사항

2022-10-24 02:48 UTC, sangwoong03 requested changes
도영님 해당 PR이 어떤 기능을 하는지 구체적으로 적어주세요.

보고서의 제목이 단순 가격순, 최신순 필터 기능이라고 애매하게 적혀있기보다는 다음과 같은 제목이 좋을 것 같네요.

`메인페이지 상품리스트 필터링 기능 추가`

PR 분리 후 푸시해주시면 리뷰 다시 진행할게요!

2022-10-24 02:48 UTC, sangwoong03 commented on db/migrations/20221021075130_update_carts_table.sql
데이터베이스 수정 관련된 PR은 분리해서 다른 PR로 올려주세요.

또한 기존 migration 이력을 건들지 않고 새로운 파일을 작성하여 데이터베이스의 수정 내역을 관리해주세요.

2022-10-25 02:38 UTC, sangwoong03 requested changes
고생하셨습니다 도영님!

2022-10-25 02:38 UTC, sangwoong03 commented on services/productService.js
> +    limit = +limit;
`offset`과 `limit`을 integer로 변경하여 호출하는 경우 service가 아니라 controller단에서 변경 후 호출하도록 변경해주세요!

2022-10-25 02:38 UTC, sangwoong03 commented on services/productService.js
> +      }
sort 값에 따라 특정 상품을 정렬하기 위한 목적으로 작성해주신 코드의 의도가 좋습니다!

다만, 정렬을 해야하는 기준이 늘어날 때마다 조건문도 같이 늘어나게 되는 문제가 발생합니다.

만약 함수 내부에서 객체로 관리를 하는 방법도 고려해볼 수 있을 것 같아요.

sort에 대한 값을 인자로 받는 함수 내부에서 sort에 대한 값들을 객체로 관리할 수 있습니다.
sort가 인자로 들어왔을 경우 함수 내부 객체의 key 값과 동일하다면 그에 대한 value를 반환하도록 작성하면 좋을 것 같네요!

```javascript
function orderBy(sort) {
  const sortSet = {
    old: 'p.id',
    new: 'p.id desc',
    ...  
  }
  return sort ? sortSet[sort] : 'p.id' // (sort 값 없다면 default value)
}

2022-10-25 23:46 UTC, sangwoong03 requested changes

2022-10-25 23:46 UTC, sangwoong03 commented on services/productService.js
> +      console.log(sort)
불필요한 console.log() 코드는 push 전 체크하여 삭제해주세요~!
```suggestion
```

2022-10-25 23:46 UTC, sangwoong03 commented on models/productDao.js
> +        DISTINCT
도영님! distinct를 안넣었을 때와의 결과 차이가 있을까요??

2022-10-25 23:46 UTC, sangwoong03 commented on services/productService.js
> +     sort = orderBy(sort)
잘 작성해주신 것 같네요!

다른 작성법도 오후에 같이 알아보면 좋을 것 같습니다!

2022-10-26 23:54 UTC, sangwoong03 requested changes
고생하셨습니다!

한 부분만 수정 후 다시 push 해주세요~!

2022-10-26 23:54 UTC, sangwoong03 commented on services/productService.js
> +     sort = orderBy(sort)
인자로 들어오는 sort에 대해 서비스 로직을 처리하는 것이 아니라 해당 부분은 Dao로 옮기는 게 좋을 것 같네요!

2022-10-27 00:09 UTC, JeongDoYoung2 commented on services/productService.js
> +     sort = orderBy(sort)
수정 완료했습니다!

2022-10-27 00:31 UTC, sangwoong03 approved these changes
LGTM 👍

2022-10-27 00:32 UTC, merged